kind: Service
apiVersion: v1
metadata:
  name: jupyterlab
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | indent 2 }}
spec:
  selector:
    app.kubernetes.io/name: jupyterlab
  type: ClusterIP
  ports:
    - targetPort: http
      port: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | indent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: jupyterlab
  ports:
  - targetPort: http
    port: 8888
