name: Continuous Integration

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade black pytest sh
      - name: Check Python formatting
        run: |
          set -eux
          black --check tests/

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest sh
      - name: Running addons tests
        run: |
          set -x
          sudo snap install microk8s --classic --channel=latest/edge
          sudo microk8s status --wait-ready --timeout 600
          sudo microk8s addons repo add testing .
          pytest -s ./tests/test-addons.py
          sudo snap remove microk8s --purge
